### ISSUE TITLE
I have a problem starting the bot

### ISSUE THREAD

**Issue by crysomemoreplease2** [NotReeceHarris/EconomyDiscord-Bot#6]
Help, i cant start the bot because the error didnt found the "discord" module
![Screenshot_2021-08-05-13-26-47-085_com android chrome](https://user-images.githubusercontent.com/73569397/128296275-34e9f757-f205-44ce-bc8a-dcdbb60f488a.png)
 What to do?

**Comment by jvhdis** [comment]
The error is called ModuleNotFoundError, meaning it can't find the "discord" module anywhere in your site-packages. This simply means you haven't installed the discord module yet. 

Run this in your terminal:
pip install -U discord

If that doesn't work and gives an error, run:
py -m pip install -U discord

The same counts for every other module it can't find, then you just have to replace "discord" with the given module name in the command for the terminal.

**Comment by NotReeceHarris** [comment]
@jvhdis thankyou for helping out.

@crysomemoreplease2 sorry but this project is kinda stoped, if you want there to be functional features you will have to add to the bot

**Comment by crysomemoreplease2** [comment]
@jvhdis Thank you

**Comment by crysomemoreplease2** [comment]
@jvhdis but what if starts a FileNotFoundError?

**Comment by NotReeceHarris** [comment]
It's either a file is not being generated which means you need to run the bot with elevated permissions(Sudo or admin), or there is a file you may have accidentally deleted > @jvhdis but what if starts a FileNotFoundError?
